# **PyTorch Fundamentals**

In [1]:
print("Hello I'm excited to learn PyTorch!")

Hello I'm excited to learn PyTorch!


In [2]:
!nvidia-smi

Tue May  2 03:46:19 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   39C    P8     9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [3]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
print(torch.__version__) 

2.0.0+cu118


# **Introduction to PyTorch Tensors**

In [4]:
#creating tensors
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
#get tensor back as python int
scalar.item()

7

In [7]:
#vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [8]:
vector.ndim 

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
#MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
print(MATRIX[0])
print(MATRIX[1])

tensor([7, 8])
tensor([ 9, 10])


In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
#TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [2, 4, 5],
                        [3, 6, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [2, 4, 5],
         [3, 6, 9]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
TENSOR[0]

tensor([[1, 2, 3],
        [2, 4, 5],
        [3, 6, 9]])

# **Creating random tensors in PyTorch**

### Random Tensors
Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

```Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers```



In [18]:
#Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor, random_tensor.ndim

(tensor([[0.7820, 0.6148, 0.8140, 0.0165],
         [0.2917, 0.8597, 0.3428, 0.2477],
         [0.4768, 0.8200, 0.7340, 0.2542]]),
 2)

In [19]:
#Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) #height, width, color channelS(R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## **Creating tensors with zeroes and ones in PyTorch**

In [20]:
#Create a tensor of all zeroes
zeros = torch.zeros(size=(3, 4))
print(zeros)
print(zeros*random_tensor) #masks random_tensor, so the model will ignore the elements of the random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [21]:
#create a tensor of all ones
ones = torch.ones(size=(3, 4))
print(ones)
print(ones.dtype) #dtype shows the datatype of the tensor, which is, unless specified otherwise, always float32

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
torch.float32


## **Craeting tensors in a range**

In [22]:
#create a tensor with elements between range 1 to 10
one_to_ten = torch.arange(1, 11)
print(one_to_ten)
#define step between the range
step_tensor = torch.arange(start=1, end=1000, step=77)
print(step_tensor)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
tensor([  1,  78, 155, 232, 309, 386, 463, 540, 617, 694, 771, 848, 925])


In [23]:
#create a tnsor with the same shape of another tensors but with different elements
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## **Dealing with tensor datatypes**
3 big error of PyTorch

1.   Tensor is not right datatype 
2.   Tensor is not right shape
3.   Tensor is not on the rigth device



In [24]:
#It is possible to change the default datatype of a tensor
#device='cuda' will store the tensor in GPU. If two tensors are in an operation and they are stored in different places, PyTorch will throw an error 
#requires_grad->whether or not to take record of gradients with this tensor's operations
float32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None, device=None, requires_grad=False)
print(float32_tensor.dtype)
float16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float16)
print(float16_tensor.dtype)

torch.float32
torch.float16


In [25]:
#assign different datatype to a tensor
float_16 = float32_tensor.type(torch.float16)
float_16.dtype

torch.float16

## **Getting tensor attributes (information about tensors)**


1.   get datatype: ```torch.dtype```
2.   get shape: ```torch.shape```
3.   get device(CPU or GPU): ```torch.device```



In [26]:
some_tensor = torch.rand(3, 4)
print(some_tensor.dtype)
print(some_tensor.shape)
print(some_tensor.device)

torch.float32
torch.Size([3, 4])
cpu


## **Manipulating Tensors (tensor operations)**

In [27]:
#Addition of a number to every element of a tensor
tensor = torch.tensor([1, 3, 4])
print(tensor + 10)
#Multiplication
#for in-place replacement tensor = tensor * 10
print(tensor * 10)
#Subtraction
print(tensor - 10)

tensor([11, 13, 14])
tensor([10, 30, 40])
tensor([-9, -7, -6])


In [28]:
#in-built functions
print(torch.mul(tensor, 10))
print(torch.add(tensor, 10))

tensor([10, 30, 40])
tensor([11, 13, 14])


## **Matrix multiplication (part 1)**

In [29]:
import torch
tensor = torch.tensor([1, 2, 3])
torch.matmul(tensor, tensor)

tensor(14)

## **Matrix multiplication (part 2: two main rules of matrix multiplication)**

In [30]:
#Another way of matrix multiplication
tensor @ tensor

tensor(14)

## **Matrix multiplication (part 3: dealing with shape errors)**

In [31]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])
#Another way of matrix multiplication is using alias of torch.matmul(): torch.mm()
torch.mm(tensor_A, tensor_B.T) #if tensor_B is a matrix, then the transpose matrix of tensor_B would be defined by 'tensor_B.T' inpytorch

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

# **Finding the min, max, mean and sum of tensors (tensor aggregation)**

In [32]:
x = torch.arange(1, 100, 10)
print(x, x.dtype)

#finding the minimum element of the matrix
print (torch.min(x), x.min())

#finding the maximum element of the matrix
print(torch.max(x), x.max())

#finding the mean of all the elements of a matrix
#torch.mean()/'sometensor'.mean() functions don't work with int64 datatype. so we change the datatype of 'x' to float32 using -> x.type(torch.float32)
print(torch.mean(x.type(torch.float32)), x.type(torch.float32).mean())

#finding the sum of all the elemenys of a matrix
print(torch.sum(x), x.sum())

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]) torch.int64
tensor(1) tensor(1)
tensor(91) tensor(91)
tensor(46.) tensor(46.)
tensor(460) tensor(460)


# **Finding the positional min and max of tensors**

In [33]:
#Finding the index of the minimum value of matrix with argmin() function
x.argmin()

tensor(0)

In [34]:
x[0]

tensor(1)

In [35]:
#Finding the indx of the maximum value of the matrix with argmax() function
x.argmax()

tensor(9)

In [36]:
x[9]

tensor(91)

## **Reshaping, viewing and stacking tensors**



* Reshaping - reshapes an input tensor to a defined shape
* View - return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine mutiple tensors on top of each other or side by side
* Squeez - removes all  ```1``` dimensions from the tensor
* Unsqueez - adds a ```1``` dimension to a target tensor
* Permute - return a view of the input with dimensions permuted (swapped) in a certain way 



In [37]:
y = torch.arange(1., 10.)
y, y.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [38]:
#reshape dimension has to be compatible with the original size of the tensor
#if we did 'y.reshape(2, 9)' or 'y.reshape(9, 9)' there would be an error because these dimensions are not compatible with the orgignal size of y
#y.shape=9, y_reshaped.shape=1x9=9
y_reshaped1 = y.reshape(1, 9)
y_reshaped2 = y.reshape(9, 1)
print(y_reshaped1, y_reshaped1.shape)
print(y_reshaped2, y_reshaped2.shape)

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]) torch.Size([1, 9])
tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]]) torch.Size([9, 1])


In [39]:
#z.shape=10, z_reshaped.shape=5x2=10
z = torch.arange(1., 11.)
print(z, z.shape)
z_reshaped = z.reshape(5, 2)
print(z_reshaped)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]) torch.Size([10])
tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])


In [40]:
#m.shape=12, m_reshaped.shape=3x4=12
m = torch.arange(1., 13.)
print(m, m.shape)
m_reshaped = m.reshape(3, 4)
print(m_reshaped)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]) torch.Size([12])
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


In [41]:
#change the view of a tensor
#remember that the 'view' function shares the memory of the original tensor
j = y.view(9, 1)
j, y

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [42]:
#changing j will bring the same positional changes to y
#same as 'reshape' funxtion, just the memory of the reshaped matrix will be the same as the original matrix
j[0] = 5.
j, y 

(tensor([[5.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [43]:
#stacking tensors
y_stacked1 = torch.stack([y, y, y, y], dim=0) #stack on top of each other
y_stacked2 = torch.stack([y, y, y, y], dim=1) #stack side by side
print(y_stacked1)
print(y_stacked2)

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])
tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])


## **Squeezing, unsqueezing, and permuting tensors**

In [44]:
y_reshaped1.squeeze(), y_reshaped1.squeeze().shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [45]:
#squeeze() function does not change the original shape of the tensor in the memory
y_reshaped1.shape

torch.Size([1, 9])

In [46]:
#unsqueeze() function adds a single dimension to target tensor at a specific dimension
y_squeezed = y_reshaped1.squeeze()
print(y_squeezed, y_squeezed.shape)
unsqueezed = y_squeezed.unsqueeze(dim=0)
print(unsqueezed, unsqueezed.shape)

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]) torch.Size([9])
tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]) torch.Size([1, 9])


In [47]:
unsqueezed2 = y_squeezed.unsqueeze(dim=1)
unsqueezed2, unsqueezed2.shape

(tensor([[5.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [48]:
#torch.permute() function rearranges the dimensions of a matrix in a specified order
#permuted tensor share the same meory as the original tensor
random_image_size_tensor_permuted1 = random_image_size_tensor.permute(2, 0, 1)
print(random_image_size_tensor_permuted1.shape)
#another way of using the permute() function
random_image_size_tensor_permuted2 = torch.permute(random_image_size_tensor, (2, 0, 1))
print(random_image_size_tensor_permuted2.shape)

torch.Size([3, 224, 224])
torch.Size([3, 224, 224])


In [49]:
#the tensors share the same meory
random_image_size_tensor[0, 0, 0] = 23
print(random_image_size_tensor[0, 0, 0])
print(random_image_size_tensor_permuted1[0, 0, 0])

tensor(23.)
tensor(23.)


## **Selecting data from tensors (indexing)**

In [99]:
#tensor indexing
sample = torch.arange(1., 10.).reshape(1, 3, 3)
sample, sample.shape

(tensor([[[1., 2., 3.],
          [4., 5., 6.],
          [7., 8., 9.]]]),
 torch.Size([1, 3, 3]))

In [90]:
print(sample[0])

tensor([1., 2., 3.])


In [93]:
print(sample[0][0])
print(sample[0, 0])

tensor(1.)
tensor(1.)


In [53]:
print(sample[0][0][0])
print(sample[0, 0, 0])

tensor(1.)
tensor(1.)


In [100]:
sample[:, :, 1]

tensor([[2., 5., 8.]])

In [55]:
sample[:, 1, 1]

tensor([5.])

In [56]:
sample[0, 0, :]

tensor([1., 2., 3.])

## **PyTorch and NumPy**

In [57]:
#convert numpy array into pytorch tensor with torch.from_numpy()
import numpy as np
array = np.arange(1., 8.)
#numpy array default datatype = float64, so the pytorch tensor datatype would be float64, instead of default tensor datatype float32
#we can convert the float64 tensor to float32 tensor with type()
np_tensor = torch.from_numpy(array).type(torch.float32)
array, np_tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [58]:
#convert pytorch tensor to numpy array with numpy()
#as pytorch default datatype is float32, after coverting to numpy array the array's daattype would be float32, not the default nump array datatype float64
tensor_n = torch.ones(7)
np_array = tensor_n.numpy()
tensor_n, np_array

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [59]:
#adding 1 to all the elements of the numpy array
print(array + 1)
#adding 1 to all the elements of a tensor
print(np_tensor + 1)

[2. 3. 4. 5. 6. 7. 8.]
tensor([2., 3., 4., 5., 6., 7., 8.])


## **PyTorch reproducibility (taking the random out of the random)**

In [60]:
rand_tensor_a = torch.rand(3, 4)
rand_tensor_b = torch.rand(3, 4)
print(rand_tensor_a)
print(rand_tensor_b)
print(rand_tensor_a == rand_tensor_b)

tensor([[0.0127, 0.5136, 0.1779, 0.6042],
        [0.2149, 0.5860, 0.9203, 0.2655],
        [0.2619, 0.9350, 0.4402, 0.2477]])
tensor([[0.1944, 0.8546, 0.1989, 0.2131],
        [0.7333, 0.8472, 0.6471, 0.2835],
        [0.9325, 0.6103, 0.5239, 0.3916]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [61]:
#generate random tensors but with same number so that the code is reproducible: torch.manual_seed(RANDOM_SEED)
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
rand_tensor_c = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
rand_tensor_d = torch.rand(3, 4)

print(rand_tensor_c)
print(rand_tensor_d)
print(rand_tensor_c == rand_tensor_d)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## **Different ways of accessing a GPU in PyTorch**

GPU makes computations fatser.

In [62]:
!nvidia-smi

Tue May  2 03:46:24 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   38C    P8     9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [63]:
#check for GPU access with PyTorch
torch.cuda.is_available()

True

In [64]:
#setup device agnostic code
#tell pytorch to use gpu when available, otherwise, use cpu
if torch.cuda.is_available():
  device = 'cuda'
else:
  device = 'cpu'

print(device)

cuda


In [65]:
#count the number of devices
#if we are running a huge model we might want to distribute the work process between mutiple GPUs, that;s why we want to count the numbe rof devices 
torch.cuda.device_count()

1

## **Setting up device agnostic code and putting tensors on and off the GPU**

In [66]:
tensor_e = torch.tensor([1, 2, 3])
tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [67]:
#move a tensor to GPU (if available) with the to(device) function
#We are working with one GPU, that is why the index shows 0, if we use more than one GPUs, then the index will be different
tensor_on_gpu = tensor_e.to(device)
tensor_on_gpu.device

device(type='cuda', index=0)

In [68]:
#if tensor is on GPU, can't transform it to numpy. NumPy only works on CPU
#Moving tensor back to CPU
#use the cpu() function to bring tensor back to CPU
#tesnor_on_gpu will stay in GPU, a copy of the tensor will be stored on CPU
tensor_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_on_cpu

array([1, 2, 3])

## **PyTorch fundamentals excersies and extra-curriculums**

## Create a random tensor with shape (7, 7)

In [69]:
prb_tensor1 = torch.rand(7, 7)
prb_tensor1

tensor([[0.8694, 0.5677, 0.7411, 0.4294, 0.8854, 0.5739, 0.2666],
        [0.6274, 0.2696, 0.4414, 0.2969, 0.8317, 0.1053, 0.2695],
        [0.3588, 0.1994, 0.5472, 0.0062, 0.9516, 0.0753, 0.8860],
        [0.5832, 0.3376, 0.8090, 0.5779, 0.9040, 0.5547, 0.3423],
        [0.6343, 0.3644, 0.7104, 0.9464, 0.7890, 0.2814, 0.7886],
        [0.5895, 0.7539, 0.1952, 0.0050, 0.3068, 0.1165, 0.9103],
        [0.6440, 0.7071, 0.6581, 0.4913, 0.8913, 0.1447, 0.5315]])

## Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor)

In [70]:
prb_tensor2 = torch.rand(1, 7)
print(prb_tensor2)

tensor([[0.1587, 0.6542, 0.3278, 0.6532, 0.3958, 0.9147, 0.2036]])


In [71]:
print(prb_tensor1 @ prb_tensor2.T)

tensor([[1.9625],
        [1.0950],
        [0.9967],
        [1.8910],
        [1.9205],
        [1.0674],
        [1.6949]])


## Set the random seed to 0 and do excersises 2 & 3 over again.

In [72]:
torch.manual_seed(0)
another_tensor1 = torch.rand(7, 7)
torch.manual_seed(0)
another_tensor2 = torch.rand(1, 7)
print(another_tensor1)
print(another_tensor2)

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])
tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]])


In [73]:
print(another_tensor1 @ another_tensor2.T)

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])


## Speaking of random seeds, we saw how to set it with ```torch.manual_seed()``` but is there a GPU equivalent? (hint: you'll need to look into the documentation for ```torch.cuda``` for thsi one). If there is, set the GPU random seed to ```1234```

In [74]:
torch.cuda.manual_seed(1234)

## Create two random tensors of shape ```(2, 3)``` and send them both to the GPU (you'll need access to a GPU for this). Set ```torch.manual_seed(1234)``` when creating the tensors (this doesn't have to be the GPU random seed).

In [75]:
torch.manual_seed(1234)
prb_tensor3 = torch.rand(2, 3)
torch.manual_seed(1234)
prb_tensor4 = torch.rand(2, 3)
gpu_tensor1 = prb_tensor3.to(device)
gpu_tensor2 = prb_tensor4.to(device)
print(gpu_tensor1)
print(gpu_tensor2)

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')


## Perform matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [76]:
mult = gpu_tensor1 @ gpu_tensor2.T
print(mult)

tensor([[0.2299, 0.2161],
        [0.2161, 0.6287]], device='cuda:0')


## Find the maximum and the minimum valuse of the output of 7

In [77]:
print(mult.max())
print(mult.min())

tensor(0.6287, device='cuda:0')
tensor(0.2161, device='cuda:0')


## Find the maximum and minimum index values of the output of 7

In [78]:
print(mult.argmax())
print(mult.argmin())

tensor(3, device='cuda:0')
tensor(1, device='cuda:0')


## Make a random tnesor with shape ```(1, 1, 1, 10)``` and then create a new tensor with all the ```1``` dimensions removed to be left with a tensor of shape ```10```. Set the seed to ```7``` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [79]:
torch.manual_seed(7)
unsqueeze = torch.rand(1, 1, 1, 10)
print(unsqueeze, unsqueeze.shape)
squeeze = unsqueeze.squeeze(dim=[0, 1, 2])
print(squeeze, squeeze.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
